server:
  port: 8081
  #servlet:
    #context-path: /campus

#日志
logging:
  #当前项目下生成springboot.log日志
  file: campus.log
  #设置日志文件大小
  file.max-size: 100MB
  #保存三十天的日志
  file.max-history: 30
  level:
    root: info
    atlan.ceer: info
    atlan.ceer.mapper: debug

#数据库连接信息
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: campus
    password: 12345678
    #配置druid为数据源
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池的配置信息
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(去掉log4j才能正常使用
    filters: stat,wall
    #filters:
    #commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #配置redis地址
  redis:
    host: 104.238.154.81
    password:

mybatis:
  #配置mapper  xml所在位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名匹配
    map-underscore-to-camel-case: true